### ISSUE TITLE
Food icon hides happiness and is not clickable

### ISSUE THREAD

**Issue by datagutten** [Beast-Masters-addons/feed-o-matic#1]
The addon replaces the happiness icon with a symbol of the food, making the happiness invisible. It should also be possible to click the icon to feed the pet.

**Comment by ShaunaGordon** [comment]
In tests on my own fork, the FOM icon is _behind_ the happiness icon when in a not-happy state, save for the number of feeds needed for full happiness, which sits on top. Being behind the happiness icon makes the FOM button unclickable.

However, when I was testing to see what was and wasn't working, I found that the `/click FOM_FeedButton` macro _does_ still work. This suggests that this issue is only one of layering and hit targets and not the button being fundamentally broken.

**Comment by datagutten** [comment]
Works well with moved icon.
