### ISSUE TITLE
Any use for this in BfA?

### ISSUE THREAD

**Issue by datagutten** [Beast-Masters-addons/feed-o-matic#3]
Is there any point in feeding your pet in BfA? There is no happiness, but will feeding the pet heal it?
I tried feeding my pet with something I had in my bags, but it was too low level.
I am used to press shift+p too see information about my hunter pet and it’s diet, but now it was only battle pets there.

**Comment by ShaunaGordon** [comment]
It's been a _long_ time since I played a hunter with any regularity, but as I recall, feeding still does heal it. The removal of the happiness and run-away mechanic drastically decreased the usefulness for FOM in Retail, though. The later changes further made pets even more low-maintenance and even somewhat generic, requiring essentially zero upkeep (you _can_ feed them, but I don't think they derive much, if any benefit from them anymore).

**Comment by datagutten** [comment]
I made an addon that I wanted to work on both platforms, so I wrote a LibProfessions to make a wrapper around the API to be able to make cross-platform addons. To avoid maintaining the API calls both here and in the library I rewrote this to use the library. This makes FOM work on both BfA and classic. This also simplifies the versioning, instead of seeing the classic version as a separate addon starting at v1.0 I can continue the master branch making a v9.0 of FOM working for both platforms.
